// const colors = [ 
//     [ 'red' ],
//     [ 'red', 'darken-1' ],
//     [ 'red', 'darken-2' ],
//     [ 'red', 'darken-3' ],
//     [ 'red', 'darken-4' ],
//     [ 'pink' ],
//     [ 'pink', 'darken-1' ],
//     [ 'pink', 'darken-2' ],
//     [ 'pink', 'darken-3' ],
//     [ 'pink', 'darken-4' ],
//     [ 'purple' ],
//     [ 'purple', 'darken-1' ],
//     [ 'purple', 'darken-2' ],
//     [ 'purple', 'darken-3' ],
//     [ 'purple', 'darken-4' ],
//     [ 'deep-purple' ],
//     [ 'deep-purple', 'darken-1' ],
//     [ 'deep-purple', 'darken-2' ],
//     [ 'deep-purple', 'darken-3' ],
//     [ 'deep-purple', 'darken-4' ],
//     [ 'indigo' ],
//     [ 'indigo', 'darken-1' ],
//     [ 'indigo', 'darken-2' ],
//     [ 'indigo', 'darken-3' ],
//     [ 'indigo', 'darken-4' ],
//     [ 'blue' ],
//     [ 'blue', 'darken-1' ],
//     [ 'blue', 'darken-2' ],
//     [ 'blue', 'darken-3' ],
//     [ 'blue', 'darken-4' ],
//     [ 'light-blue' ],
//     [ 'light-blue', 'darken-1' ],
//     [ 'light-blue', 'darken-2' ],
//     [ 'light-blue', 'darken-3' ],
//     [ 'light-blue', 'darken-4' ],
//     [ 'cyan' ],
//     [ 'cyan', 'darken-1' ],
//     [ 'cyan', 'darken-2' ],
//     [ 'cyan', 'darken-3' ],
//     [ 'cyan', 'darken-4' ],
//     [ 'teal' ],
//     [ 'teal', 'darken-1' ],
//     [ 'teal', 'darken-2' ],
//     [ 'teal', 'darken-3' ],
//     [ 'teal', 'darken-4' ],
//     [ 'green' ],
//     [ 'green', 'darken-1' ],
//     [ 'green', 'darken-2' ],
//     [ 'green', 'darken-3' ],
//     [ 'green', 'darken-4' ],
//     [ 'light-green' ],
//     [ 'light-green', 'darken-1' ],
//     [ 'light-green', 'darken-2' ],
//     [ 'light-green', 'darken-3' ],
//     [ 'light-green', 'darken-4' ],
//     [ 'amber' ],
//     [ 'amber', 'darken-1' ],
//     [ 'amber', 'darken-2' ],
//     [ 'amber', 'darken-3' ],
//     [ 'amber', 'darken-4' ],
//     [ 'orange' ],
//     [ 'orange', 'darken-1' ],
//     [ 'orange', 'darken-2' ],
//     [ 'orange', 'darken-3' ],
//     [ 'orange', 'darken-4' ],
//     [ 'deep-orange' ],
//     [ 'deep-orange', 'darken-1' ],
//     [ 'deep-orange', 'darken-2' ],
//     [ 'deep-orange', 'darken-3' ],
//     [ 'deep-orange', 'darken-4' ],
//     [ 'brown' ],
//     [ 'brown', 'darken-1' ],
//     [ 'brown', 'darken-2' ],
//     [ 'brown', 'darken-3' ],
//     [ 'brown', 'darken-4' ],
//     [ 'blue-grey' ],
//     [ 'blue-grey', 'darken-1' ],
//     [ 'blue-grey', 'darken-2' ],
//     [ 'blue-grey', 'darken-3' ],
//     [ 'blue-grey', 'darken-4' ],
//     [ 'black' ] 
// ]

export const colors = [ [ [ 'red' ],
[ 'red', 'darken-1' ],
[ 'red', 'darken-2' ],
[ 'red', 'darken-3' ],
[ 'red', 'darken-4' ] ],
[ [ 'pink' ],
[ 'pink', 'darken-1' ],
[ 'pink', 'darken-2' ],
[ 'pink', 'darken-3' ],
[ 'pink', 'darken-4' ] ],
[ [ 'purple' ],
[ 'purple', 'darken-1' ],
[ 'purple', 'darken-2' ],
[ 'purple', 'darken-3' ],
[ 'purple', 'darken-4' ] ],
[ [ 'deep-purple' ],
[ 'deep-purple', 'darken-1' ],
[ 'deep-purple', 'darken-2' ],
[ 'deep-purple', 'darken-3' ],
[ 'deep-purple', 'darken-4' ] ],
[ [ 'indigo' ],
[ 'indigo', 'darken-1' ],
[ 'indigo', 'darken-2' ],
[ 'indigo', 'darken-3' ],
[ 'indigo', 'darken-4' ] ],
[ [ 'blue' ],
[ 'blue', 'darken-1' ],
[ 'blue', 'darken-2' ],
[ 'blue', 'darken-3' ],
[ 'blue', 'darken-4' ] ],
[ [ 'light-blue' ],
[ 'light-blue', 'darken-1' ],
[ 'light-blue', 'darken-2' ],
[ 'light-blue', 'darken-3' ],
[ 'light-blue', 'darken-4' ] ],
[ [ 'cyan' ],
[ 'cyan', 'darken-1' ],
[ 'cyan', 'darken-2' ],
[ 'cyan', 'darken-3' ],
[ 'cyan', 'darken-4' ] ],
[ [ 'teal' ],
[ 'teal', 'darken-1' ],
[ 'teal', 'darken-2' ],
[ 'teal', 'darken-3' ],
[ 'teal', 'darken-4' ] ],
[ [ 'green' ],
[ 'green', 'darken-1' ],
[ 'green', 'darken-2' ],
[ 'green', 'darken-3' ],
[ 'green', 'darken-4' ] ],
[ [ 'light-green' ],
[ 'light-green', 'darken-1' ],
[ 'light-green', 'darken-2' ],
[ 'light-green', 'darken-3' ],
[ 'light-green', 'darken-4' ] ],
[ [ 'amber' ],
[ 'amber', 'darken-1' ],
[ 'amber', 'darken-2' ],
[ 'amber', 'darken-3' ],
[ 'amber', 'darken-4' ] ],
[ [ 'orange' ],
[ 'orange', 'darken-1' ],
[ 'orange', 'darken-2' ],
[ 'orange', 'darken-3' ],
[ 'orange', 'darken-4' ] ],
[ [ 'deep-orange' ],
[ 'deep-orange', 'darken-1' ],
[ 'deep-orange', 'darken-2' ],
[ 'deep-orange', 'darken-3' ],
[ 'deep-orange', 'darken-4' ] ],
[ [ 'brown' ],
[ 'brown', 'darken-1' ],
[ 'brown', 'darken-2' ],
[ 'brown', 'darken-3' ],
[ 'brown', 'darken-4' ] ],
[ [ 'blue-grey' ],
[ 'blue-grey', 'darken-1' ],
[ 'blue-grey', 'darken-2' ],
[ 'blue-grey', 'darken-3' ],
[ 'blue-grey', 'darken-4' ] ],
[ [ 'black' ] ] ]

// export const colors = [ [ [ 'red-text' ],
// [ 'red-text', 'text-darken-1' ],
// [ 'red-text', 'text-darken-2' ],
// [ 'red-text', 'text-darken-3' ],
// [ 'red-text', 'text-darken-4' ] ],
// [ [ 'pink-text' ],
// [ 'pink-text', 'text-darken-1' ],
// [ 'pink-text', 'text-darken-2' ],
// [ 'pink-text', 'text-darken-3' ],
// [ 'pink-text', 'text-darken-4' ] ],
// [ [ 'purple-text' ],
// [ 'purple-text', 'text-darken-1' ],
// [ 'purple-text', 'text-darken-2' ],
// [ 'purple-text', 'text-darken-3' ],
// [ 'purple-text', 'text-darken-4' ] ],
// [ [ 'deep-purple-text' ],
// [ 'deep-purple-text', 'text-darken-1' ],
// [ 'deep-purple-text', 'text-darken-2' ],
// [ 'deep-purple-text', 'text-darken-3' ],
// [ 'deep-purple-text', 'text-darken-4' ] ],
// [ [ 'indigo-text' ],
// [ 'indigo-text', 'text-darken-1' ],
// [ 'indigo-text', 'text-darken-2' ],
// [ 'indigo-text', 'text-darken-3' ],
// [ 'indigo-text', 'text-darken-4' ] ],
// [ [ 'blue-text' ],
// [ 'blue-text', 'text-darken-1' ],
// [ 'blue-text', 'text-darken-2' ],
// [ 'blue-text', 'text-darken-3' ],
// [ 'blue-text', 'text-darken-4' ] ],
// [ [ 'light-blue-text' ],
// [ 'light-blue-text', 'text-darken-1' ],
// [ 'light-blue-text', 'text-darken-2' ],
// [ 'light-blue-text', 'text-darken-3' ],
// [ 'light-blue-text', 'text-darken-4' ] ],
// [ [ 'cyan-text' ],
// [ 'cyan-text', 'text-darken-1' ],
// [ 'cyan-text', 'text-darken-2' ],
// [ 'cyan-text', 'text-darken-3' ],
// [ 'cyan-text', 'text-darken-4' ] ],
// [ [ 'teal-text' ],
// [ 'teal-text', 'text-darken-1' ],
// [ 'teal-text', 'text-darken-2' ],
// [ 'teal-text', 'text-darken-3' ],
// [ 'teal-text', 'text-darken-4' ] ],
// [ [ 'green-text' ],
// [ 'green-text', 'text-darken-1' ],
// [ 'green-text', 'text-darken-2' ],
// [ 'green-text', 'text-darken-3' ],
// [ 'green-text', 'text-darken-4' ] ],
// [ [ 'light-green-text' ],
// [ 'light-green-text', 'text-darken-1' ],
// [ 'light-green-text', 'text-darken-2' ],
// [ 'light-green-text', 'text-darken-3' ],
// [ 'light-green-text', 'text-darken-4' ] ],

// [ [ 'orange-text' ],
// [ 'orange-text', 'text-darken-1' ],
// [ 'orange-text', 'text-darken-2' ],
// [ 'orange-text', 'text-darken-3' ],
// [ 'orange-text', 'text-darken-4' ] ],
// [ [ 'deep-orange-text' ],
// [ 'deep-orange-text', 'text-darken-1' ],
// [ 'deep-orange-text', 'text-darken-2' ],
// [ 'deep-orange-text', 'text-darken-3' ],
// [ 'deep-orange-text', 'text-darken-4' ] ],
// [ [ 'brown-text' ],
// [ 'brown-text', 'text-darken-1' ],
// [ 'brown-text', 'text-darken-2' ],
// [ 'brown-text', 'text-darken-3' ],
// [ 'brown-text', 'text-darken-4' ] ],
// [ [ 'blue-grey-text' ],
// [ 'blue-grey-text', 'text-darken-1' ],
// [ 'blue-grey-text', 'text-darken-2' ],
// [ 'blue-grey-text', 'text-darken-3' ],
// [ 'blue-grey-text', 'text-darken-4' ] ],
// [ [ 'black-text' ] ] ]